// ...existing code...
const fs = require('fs');
const path = require('path');
require('dotenv').config();

const REQUIRED = [
  'GOOGLE_CLIENT_ID',
  'STRIPE_API_KEY',
  'API_BASE_URL',
  'DEPOMEX_API_URL',
  'APIKEY_DEPOMEX'
];

function ensureEnvs() {
  const missing = REQUIRED.filter(k => !process.env[k] || process.env[k].trim() === '');
  if (missing.length) {
    console.error('Missing required environment variables:', missing.join(', '));
    process.exit(1);
  }
}

function buildContent(envObj) {
  // JSON.stringify ensures proper escaping of values
  const body = Object.keys(envObj)
    .map(k => `  ${k}: ${JSON.stringify(envObj[k])},`)
    .join('\n');
  return `// This file is auto-generated by scripts/set-envs.js\nexport const environment = {\n${body}\n};\n`;
}

function writeFileSafe(targetPath, content) {
  fs.mkdirSync(path.dirname(targetPath), { recursive: true });
  fs.writeFileSync(targetPath, content, { encoding: 'utf8' });
}

(function main() {
  ensureEnvs();

  const base = {
    googleClientId: process.env.GOOGLE_CLIENT_ID,
    stripeApiKey: process.env.STRIPE_API_KEY,
    apiBaseUrl: process.env.API_BASE_URL,
    depomexApiUrl: process.env.DEPOMEX_API_URL,
    apikeyDepomex: process.env.APIKEY_DEPOMEX
  };

  const envDir = path.join(__dirname, '..', 'src', 'environments');

  // dev (default non-production)
  const devEnv = Object.assign({ production: false }, base);
  // prod (production true)
  const prodEnv = Object.assign({ production: true }, base);

  writeFileSafe(path.join(envDir, 'environment.ts'), buildContent(devEnv));
  writeFileSafe(path.join(envDir, 'environment.dev.ts'), buildContent(devEnv));
  writeFileSafe(path.join(envDir, 'environment.prod.ts'), buildContent(prodEnv));
})();